from __future__ import annotations

from enum import Enum, IntEnum


class LogName(str, Enum):
    APPLICATION = "Application"
    SYSTEM = "System"
    AUDIT = "Audit"


class EventCode(IntEnum):
    APPLICATION_DB_CREATE_REQUESTED = 1000
    APPLICATION_DB_CREATED = 1001
    APPLICATION_DB_ALREADY_EXISTS = 1002
    APPLICATION_DB_DROP_REQUESTED = 1003
    APPLICATION_DB_DROPPED = 1004
    APPLICATION_DB_NOT_FOUND = 1005

    SYSTEM_STARTUP = 3000
    SYSTEM_CONNECTED = 3001
    SYSTEM_ERROR = 3002
    SYSTEM_DIRECTORY_ENSURED = 3003

    AUDIT_BACKUP_STARTED = 9000
    AUDIT_BACKUP_COMPLETED = 9001
    AUDIT_RESTORE_STARTED = 9002
    AUDIT_RESTORE_COMPLETED = 9003
    AUDIT_CONFIG_CHANGED = 9004
    AUDIT_EXECUTABLE_RESOLVED = 9005
    AUDIT_MIGRATION_FILES_DELETED = 9006
